apiVersion: v1
items:
- apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    creationTimestamp: "2022-06-02T15:58:58Z"
    name: hpa-deployment
    namespace: default
    resourceVersion: "21218"
    uid: 9e547207-ad70-4aa8-9ea7-e1db2f2153dc
  spec:
    maxReplicas: 8
    metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
      type: Resource
    minReplicas: 3
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: hpa-deployment
  status:
    conditions:
    - lastTransitionTime: "2022-06-02T15:59:13Z"
      message: recommended size matches current size
      reason: ReadyForNewScale
      status: "True"
      type: AbleToScale
    - lastTransitionTime: "2022-06-02T15:59:13Z"
      message: the HPA was able to successfully calculate a replica count from cpu
        resource utilization (percentage of request)
      reason: ValidMetricFound
      status: "True"
      type: ScalingActive
    - lastTransitionTime: "2022-06-02T16:04:13Z"
      message: the desired replica count is less than the minimum replica count
      reason: TooFewReplicas
      status: "True"
      type: ScalingLimited
    currentMetrics:
    - resource:
        current:
          averageUtilization: 0
          averageValue: "0"
        name: cpu
      type: Resource
    currentReplicas: 3
    desiredReplicas: 3
kind: List
metadata:
  resourceVersion: ""
