apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hpa-deployment
  name: hpa-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hpa-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hpa-deployment
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
         limits:
          cpu: 100m
         requests:
          cpu: 100m
