apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-06-02T16:17:53Z"
  labels:
    app: hpa-deployment
  name: hpa-svc
  namespace: default
  resourceVersion: "22471"
  uid: f40c7c23-1b0d-4a71-8659-28f1deab6657
spec:
  clusterIP: 10.97.169.198
  clusterIPs:
  - 10.97.169.198
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hpa-deployment
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
